import type { ShopItem, Achievement, Expedition, FishType } from '@/types/game'

// ── Persist keys ──────────────────────────────────────────────────────────────
export const SAVE_KEY = 'k0509_petState'
export const SETTINGS_KEY = 'k0509_settings'
export const MISSIONS_KEY = 'k0509_missions'
export const SPIN_KEY = 'k0509_lastSpin'
export const LUCKY_KEY = 'k0509_lastLucky'
export const DAILY_KEY = 'k0509_dailyBonus'
export const NOTIFS_KEY = 'k0509_notifs'

// ── XP table ──────────────────────────────────────────────────────────────────
export function xpForLevel(level: number): number {
  return Math.floor(100 * Math.pow(level, 1.5))
}

// ── Decay rates (per minute offline) ─────────────────────────────────────────
export const DECAY_RATES = { mood: -0.5, hunger: -0.8, energy: -0.3 } as const

// ── Boundaries ────────────────────────────────────────────────────────────────
export const STAT_MIN = 0
export const STAT_MAX = 100

// ── Tap rewards ───────────────────────────────────────────────────────────────
export const TAP_XP_BASE = 5
export const TAP_COIN_CHANCE = 0.15
export const TAP_MOOD_BOOST = 2
export const TAP_HUNGER_COST = 0.5
export const TAP_ENERGY_COST = 0.3

// ── Audio defaults ────────────────────────────────────────────────────────────
export const AUDIO_ENABLED_DEFAULT = true
export const MUSIC_VOLUME_DEFAULT = 0.4
export const SFX_VOLUME_DEFAULT = 0.7

// ── Shop items ────────────────────────────────────────────────────────────────
export const SHOP_FOOD: ShopItem[] = [
  { id: 'kibble', name: 'Super Kibble', emoji: '🍖', description: '+30 hunger', price: 50, currency: 'coins', category: 'food', stat: { hunger: 30 } },
  { id: 'treat', name: 'Galaxy Treat', emoji: '🍬', description: '+20 mood +10 hunger', price: 80, currency: 'coins', category: 'food', stat: { mood: 20, hunger: 10 } },
  { id: 'drink', name: 'Energy Drink+', emoji: '⚡', description: '+40 energi', price: 100, currency: 'coins', category: 'food', stat: { energy: 40 } },
  { id: 'candy', name: 'Mood Candy', emoji: '🍭', description: '+35 humör', price: 90, currency: 'coins', category: 'food', stat: { mood: 35 } },
  { id: 'feast', name: 'Kunglig Fest', emoji: '🍱', description: '+100 hunger +50 mood', price: 300, currency: 'coins', category: 'food', stat: { hunger: 100, mood: 50 } },
]

export const SHOP_BOOSTS: ShopItem[] = [
  { id: 'maxmood', name: 'Max Humör', emoji: '😊', description: 'Fullt humör', price: 80, currency: 'coins', category: 'boost', stat: { mood: 100 } },
  { id: 'maxenergy', name: 'Max Energi', emoji: '⚡', description: 'Full energi', price: 80, currency: 'coins', category: 'boost', stat: { energy: 100 } },
  { id: 'maxhunger', name: 'Max Mat', emoji: '🍖', description: 'Full mat', price: 80, currency: 'coins', category: 'boost', stat: { hunger: 100 } },
  { id: 'xp500', name: '+500 XP', emoji: '⭐', description: 'XP-boost direkt', price: 200, currency: 'coins', category: 'boost' },
]

export const SHOP_HATS: ShopItem[] = [
  { id: 'hat_party', name: 'Festmössa', emoji: '🎉', description: '+3% XP', price: 100, currency: 'coins', category: 'hat' },
  { id: 'hat_cowboy', name: 'Cowboyhatt', emoji: '🤠', description: 'Cowboy-stil', price: 150, currency: 'coins', category: 'hat' },
  { id: 'hat_crown', name: 'Krona', emoji: '👑', description: '+8% Coins', price: 250, currency: 'coins', category: 'hat' },
  { id: 'hat_witch', name: 'Häxhatt', emoji: '🧙', description: 'Magisk kraft', price: 300, currency: 'coins', category: 'hat' },
  { id: 'hat_grad', name: 'Studentmössa', emoji: '🎓', description: '+10% XP', price: 300, currency: 'coins', category: 'hat' },
]

export const SHOP_ACC: ShopItem[] = [
  { id: 'acc_sun', name: 'Solglasögon', emoji: '😎', description: 'Super cool', price: 80, currency: 'coins', category: 'acc' },
  { id: 'acc_bow', name: 'Rosett', emoji: '🎀', description: '+5% Social', price: 80, currency: 'coins', category: 'acc' },
  { id: 'acc_mask', name: 'Mask', emoji: '🎭', description: '+8% Battle', price: 150, currency: 'coins', category: 'acc' },
  { id: 'acc_ring', name: 'Ring', emoji: '💍', description: 'Lyxigt', price: 200, currency: 'coins', category: 'acc' },
  { id: 'acc_star', name: 'Stjärnbricka', emoji: '⭐', description: '+10% XP', price: 250, currency: 'coins', category: 'acc' },
]

export const SHOP_AURA: ShopItem[] = [
  { id: 'aura_fire', name: 'Eldaura', emoji: '🔥', description: 'Brinnande kraft', price: 120, currency: 'coins', category: 'aura' },
  { id: 'aura_glitter', name: 'Glitteraura', emoji: '✨', description: 'Glittrande lyckliga', price: 120, currency: 'coins', category: 'aura' },
  { id: 'aura_moon', name: 'Månljusaura', emoji: '🌙', description: 'Månsken kraft', price: 200, currency: 'coins', category: 'aura' },
  { id: 'aura_rainbow', name: 'Regnbågsaura', emoji: '🌈', description: '+10% All stats', price: 350, currency: 'coins', category: 'aura' },
  { id: 'aura_star', name: 'Stjärndamm', emoji: '🌟', description: '+8% XP', price: 250, currency: 'coins', category: 'aura' },
]

export const SHOP_SKINS: ShopItem[] = [
  { id: 'skin_fire', name: 'Inferno', emoji: '🔥', description: 'Eldlook', price: 500, currency: 'coins', category: 'skin' },
  { id: 'skin_ice', name: 'Frost', emoji: '❄️', description: 'Islook', price: 500, currency: 'coins', category: 'skin' },
  { id: 'skin_gold', name: 'Guld', emoji: '💛', description: 'Guldlook', price: 1500, currency: 'coins', category: 'skin' },
  { id: 'skin_galaxy', name: 'Galaxy', emoji: '🌌', description: 'Galaxlook', price: 3000, currency: 'coins', category: 'skin' },
  { id: 'skin_ghost', name: 'Ghost', emoji: '👻', description: 'Spöklook', price: 800, currency: 'coins', category: 'skin' },
  { id: 'skin_cyber', name: 'Cyber', emoji: '🤖', description: 'Robotlook', price: 2000, currency: 'coins', category: 'skin' },
]

export const SHOP_KC: ShopItem[] = [
  { id: 'kc_aura', name: 'Kosmisk Aura', emoji: '🌠', description: 'Exklusiv aura', price: 50, currency: 'kc', category: 'aura' },
  { id: 'kc_hat', name: 'Galax-krona', emoji: '🪐', description: 'Sällsynt hatt', price: 30, currency: 'kc', category: 'hat' },
  { id: 'kc_xp', name: 'Mega XP', emoji: '🚀', description: '+1000 XP direkt', price: 20, currency: 'kc', category: 'boost' },
  { id: 'kc_revive', name: 'Full Återhämtning', emoji: '💖', description: 'Alla stats till 100', price: 15, currency: 'kc', category: 'boost', stat: { mood: 100, hunger: 100, energy: 100 } },
  { id: 'kc_shield', name: 'Streak-Sköld', emoji: '🛡️', description: 'Skyddar streaken en dag', price: 5, currency: 'kc', category: 'boost' },
  { id: 'kc_x2xp', name: '2× XP Boost', emoji: '⚡', description: '2× XP i 30 minuter', price: 10, currency: 'kc', category: 'boost' },
  { id: 'kc_dragon', name: 'Dragon-skin', emoji: '🐉', description: 'Exklusiv dragskin', price: 100, currency: 'kc', category: 'skin' },
  { id: 'kc_phoenix', name: 'Phoenix-skin', emoji: '🦅', description: 'Legendarisk fågel', price: 150, currency: 'kc', category: 'skin' },
  { id: 'kc_mega_xp', name: 'Mega XP Explosion', emoji: '💥', description: '+3000 XP direkt', price: 50, currency: 'kc', category: 'boost' },
  { id: 'kc_coinx2', name: 'Mynt Boost 1h', emoji: '🪙', description: '2× mynt i 1 timme', price: 15, currency: 'kc', category: 'boost' },
]

// ── Achievements ──────────────────────────────────────────────────────────────
export const ALL_ACHIEVEMENTS: Achievement[] = [
  { id: 'lv5', title: 'LV 5 Nybörjare', emoji: '⭐', description: 'Nå nivå 5', rarity: 'common', condition: s => s.level >= 5, reward: { xp: 100, kc: 2 } },
  { id: 'lv10', title: 'LV 10 Legend', emoji: '🌟', description: 'Nå nivå 10', rarity: 'uncommon', condition: s => s.level >= 10, reward: { xp: 300, kc: 5 } },
  { id: 'lv15', title: 'LV 15 Elite', emoji: '💫', description: 'Nå nivå 15', rarity: 'rare', condition: s => s.level >= 15, reward: { xp: 600, kc: 10 } },
  { id: 'lv20', title: 'LV 20 GOAT', emoji: '🔱', description: 'Nå nivå 20', rarity: 'legendary', condition: s => s.level >= 20, reward: { xp: 2000, kc: 30 } },
  { id: 'taps100', title: 'Klapper', emoji: '👆', description: '100 pek', rarity: 'common', condition: s => s.totalTaps >= 100, reward: { xp: 50, kc: 1 } },
  { id: 'taps1000', title: 'Pekmaskin', emoji: '🤜', description: '1 000 pek', rarity: 'uncommon', condition: s => s.totalTaps >= 1000, reward: { xp: 200, kc: 3 } },
  { id: 'taps10000', title: 'Tap God', emoji: '⚡', description: '10 000 pek', rarity: 'epic', condition: s => s.totalTaps >= 10000, reward: { xp: 1000, kc: 15 } },
  { id: 'coins1000', title: 'Tusenaire', emoji: '💰', description: 'Tjäna 1 000 mynt', rarity: 'common', condition: s => s.totalCoinsEarned >= 1000, reward: { xp: 100, kc: 2 } },
  { id: 'coins5000', title: 'Rik', emoji: '💎', description: 'Tjäna 5 000 mynt', rarity: 'uncommon', condition: s => s.totalCoinsEarned >= 5000, reward: { xp: 300, kc: 5 } },
  { id: 'coins50000', title: 'Miljonär', emoji: '🤑', description: 'Tjäna 50 000 mynt', rarity: 'epic', condition: s => s.totalCoinsEarned >= 50000, reward: { xp: 2000, kc: 25 } },
  { id: 'streak7', title: '7 Dagars Streak', emoji: '🔥', description: '7 dagar i rad', rarity: 'uncommon', condition: s => s.streak >= 7, reward: { xp: 200, kc: 5 } },
  { id: 'streak30', title: '30 Dagars Streak', emoji: '🏅', description: '30 dagar i rad', rarity: 'epic', condition: s => s.streak >= 30, reward: { xp: 1000, kc: 20 } },
  { id: 'battle5', title: 'Battle Master', emoji: '⚔️', description: 'Vinn 5 strider', rarity: 'uncommon', condition: s => s.battleWins >= 5, reward: { xp: 150, kc: 3 } },
  { id: 'battle30', title: 'Champion', emoji: '🏆', description: 'Vinn 30 strider', rarity: 'epic', condition: s => s.battleWins >= 30, reward: { xp: 800, kc: 15 } },
  { id: 'fish1', title: 'Första Fisken', emoji: '🎣', description: 'Fånga en fisk', rarity: 'common', condition: s => s.fishCaught >= 1, reward: { xp: 30, kc: 1 } },
  { id: 'fish10', title: 'Fiskare', emoji: '🐟', description: 'Fånga 10 fiskar', rarity: 'uncommon', condition: s => s.fishCaught >= 10, reward: { xp: 200, kc: 4 } },
  { id: 'fish50', title: 'Hajjägare', emoji: '🦈', description: 'Fånga 50 fiskar', rarity: 'rare', condition: s => s.fishCaught >= 50, reward: { xp: 800, kc: 12 } },
  { id: 'runner100', title: 'Sprinter', emoji: '🏃', description: 'Spring 100m', rarity: 'uncommon', condition: s => s.runnerBest >= 100, reward: { xp: 200, kc: 3 } },
  { id: 'runner500', title: 'Speed Demon', emoji: '💨', description: 'Spring 500m', rarity: 'epic', condition: s => s.runnerBest >= 500, reward: { xp: 800, kc: 12 } },
  { id: 'quest10', title: 'Uppdragsjägare', emoji: '📋', description: 'Klara 10 uppdrag', rarity: 'uncommon', condition: s => s.questsCompleted >= 10, reward: { xp: 250, kc: 4 } },
  { id: 'kc50', title: 'KC Samlare', emoji: '✨', description: 'Samla 50 KC', rarity: 'uncommon', condition: s => s.kc >= 50, reward: { xp: 200, kc: 0 } },
  { id: 'kc200', title: 'KC Rik', emoji: '💫', description: 'Samla 200 KC', rarity: 'rare', condition: s => s.kc >= 200, reward: { xp: 600, kc: 0 } },
  { id: 'bond1', title: 'Bekant', emoji: '🤝', description: 'Nå Bond Tier 1', rarity: 'common', condition: s => s.bondTier >= 1, reward: { xp: 80, kc: 1 } },
  { id: 'bond3', title: 'Vän för Livet', emoji: '💚', description: 'Nå Bond Tier 3 (Vän)', rarity: 'rare', condition: s => s.bondTier >= 3, reward: { xp: 400, kc: 8 } },
  { id: 'bond5', title: 'Soulmate', emoji: '💫', description: 'Nå Bond Tier 5 — Soulmate', rarity: 'legendary', condition: s => s.bondTier >= 5, reward: { xp: 3000, kc: 50 } },
  { id: 'prestige1', title: 'Återpräglad', emoji: '🔄', description: 'Prestige för första gången', rarity: 'epic', condition: s => s.prestigeLevel >= 1, reward: { xp: 1500, kc: 20 } },
  { id: 'post1', title: 'Flash Debutant', emoji: '📸', description: 'Publicera ditt första inlägg', rarity: 'common', condition: s => s.postCount >= 1, reward: { xp: 50, kc: 1 } },
  { id: 'post10', title: 'Flash Influencer', emoji: '⚡', description: 'Publicera 10 inlägg', rarity: 'uncommon', condition: s => s.postCount >= 10, reward: { xp: 300, kc: 5 } },
  { id: 'expedition1', title: 'Äventyrare', emoji: '🗺️', description: 'Klara en expedition', rarity: 'common', condition: s => s.expeditionsDone >= 1, reward: { xp: 100, kc: 2 } },
  { id: 'expedition5', title: 'Vilde', emoji: '🌲', description: 'Klara 5 expeditioner', rarity: 'uncommon', condition: s => s.expeditionsDone >= 5, reward: { xp: 400, kc: 7 } },
  { id: 'lv25', title: 'LV 25 Master', emoji: '🔮', description: 'Nå nivå 25', rarity: 'legendary', condition: s => s.level >= 25, reward: { xp: 5000, kc: 50 } },
  { id: 'battle100', title: 'Oövervinnerlig', emoji: '👑', description: 'Vinn 100 strider', rarity: 'legendary', condition: s => s.battleWins >= 100, reward: { xp: 3000, kc: 40 } },
  { id: 'taps50000', title: 'Tap Legend', emoji: '🌠', description: '50 000 pek', rarity: 'legendary', condition: s => s.totalTaps >= 50000, reward: { xp: 5000, kc: 60 } },
  { id: 'expedition10', title: 'Världsresenär', emoji: '🌍', description: 'Klara 10 expeditioner', rarity: 'rare', condition: s => s.expeditionsDone >= 10, reward: { xp: 1000, kc: 15 } },
  { id: 'runner1000', title: 'Marathon', emoji: '🏅', description: 'Spring 1000m', rarity: 'legendary', condition: s => s.runnerBest >= 1000, reward: { xp: 2000, kc: 25 } },
  { id: 'fish100', title: 'Fiskegud', emoji: '🐠', description: 'Fånga 100 fiskar', rarity: 'legendary', condition: s => s.fishCaught >= 100, reward: { xp: 2500, kc: 35 } },
  { id: 'coins100000', title: 'Kryptokonung', emoji: '💸', description: 'Tjäna 100 000 mynt', rarity: 'legendary', condition: s => s.totalCoinsEarned >= 100000, reward: { xp: 5000, kc: 50 } },
  { id: 'lv30', title: 'LV 30 Transcendent', emoji: '🌌', description: 'Nå nivå 30', rarity: 'legendary', condition: s => s.level >= 30, reward: { xp: 10000, kc: 100 } },
  { id: 'streak100', title: 'Centurion Streak', emoji: '🔥', description: '100 dagars streak', rarity: 'legendary', condition: s => s.streak >= 100, reward: { xp: 5000, kc: 100 } },
  { id: 'streak60', title: '60 Dagars Streak', emoji: '🔥', description: '60 dagar i rad', rarity: 'rare', condition: s => s.streak >= 60, reward: { xp: 2000, kc: 30 } },
  { id: 'taps5000', title: 'Pektusare', emoji: '👆', description: '5 000 pek', rarity: 'rare', condition: s => s.totalTaps >= 5000, reward: { xp: 500, kc: 8 } },
  { id: 'taps100000', title: 'Mega Tap God', emoji: '🌟', description: '100 000 pek', rarity: 'legendary', condition: s => s.totalTaps >= 100000, reward: { xp: 10000, kc: 100 } },
  { id: 'battle50', title: 'Veteran', emoji: '🛡️', description: 'Vinn 50 strider', rarity: 'rare', condition: s => s.battleWins >= 50, reward: { xp: 1500, kc: 20 } },
  { id: 'fish25', title: 'Fritidsfiskare', emoji: '🐠', description: 'Fånga 25 fiskar', rarity: 'rare', condition: s => s.fishCaught >= 25, reward: { xp: 500, kc: 8 } },
  { id: 'kc500', title: 'KC Miljonär', emoji: '💎', description: 'Samla 500 KC', rarity: 'legendary', condition: s => s.kc >= 500, reward: { xp: 3000, kc: 0 } },
  { id: 'bond2', title: 'Kompis', emoji: '😊', description: 'Nå Bond Tier 2 (Kompis)', rarity: 'uncommon', condition: s => s.bondTier >= 2, reward: { xp: 200, kc: 3 } },
  { id: 'bond4', title: 'Bästis', emoji: '🫶', description: 'Nå Bond Tier 4 (Bästis)', rarity: 'epic', condition: s => s.bondTier >= 4, reward: { xp: 1000, kc: 15 } },
  { id: 'prestige3', title: 'Tredubbel Prestige', emoji: '🔱', description: 'Prestige 3 gånger', rarity: 'legendary', condition: s => s.prestigeLevel >= 3, reward: { xp: 5000, kc: 75 } },
  { id: 'post25', title: 'Flash Megastar', emoji: '⭐', description: 'Publicera 25 inlägg', rarity: 'rare', condition: s => s.postCount >= 25, reward: { xp: 800, kc: 12 } },
  { id: 'expedition3', title: 'Expeditör', emoji: '🌿', description: 'Klara 3 expeditioner', rarity: 'common', condition: s => s.expeditionsDone >= 3, reward: { xp: 150, kc: 3 } },
  { id: 'expedition20', title: 'Globetrotter', emoji: '🌐', description: 'Klara 20 expeditioner', rarity: 'epic', condition: s => s.expeditionsDone >= 20, reward: { xp: 2000, kc: 30 } },
  { id: 'coins10000', title: 'Mynt-samlare', emoji: '🪙', description: 'Tjäna 10 000 mynt', rarity: 'rare', condition: s => s.totalCoinsEarned >= 10000, reward: { xp: 600, kc: 10 } },
  { id: 'runner250', title: 'Halvmaraton', emoji: '🏃', description: 'Spring 250m', rarity: 'rare', condition: s => s.runnerBest >= 250, reward: { xp: 400, kc: 6 } },
  { id: 'quest50', title: 'Quest Master', emoji: '📜', description: 'Klara 50 uppdrag', rarity: 'epic', condition: s => s.questsCompleted >= 50, reward: { xp: 1500, kc: 20 } },
  { id: 'quest100', title: 'Quest Legend', emoji: '🏆', description: 'Klara 100 uppdrag', rarity: 'legendary', condition: s => s.questsCompleted >= 100, reward: { xp: 5000, kc: 50 } },
  { id: 'lv40', title: 'LV 40 Gudomlig', emoji: '✨', description: 'Nå nivå 40', rarity: 'legendary', condition: s => s.level >= 40, reward: { xp: 20000, kc: 200 } },
]

// ── Expeditions ───────────────────────────────────────────────────────────────
export const EXPEDITIONS: Expedition[] = [
  { id: 'forest', name: 'Djupa Skogen', emoji: '🌲', description: 'Sök äventyr i skogen', duration: 5, difficulty: 'easy', reward: { xp: 100, coins: 50, kc: 1 }, unlockLevel: 1 },
  { id: 'cave', name: 'Mörk Grotta', emoji: '🕯️', description: 'Utforska grottan', duration: 15, difficulty: 'easy', reward: { xp: 200, coins: 100, kc: 2 }, unlockLevel: 2 },
  { id: 'ocean', name: 'Djuphav', emoji: '🌊', description: 'Dyk ned i havet', duration: 30, difficulty: 'normal', reward: { xp: 400, coins: 200, kc: 5 }, unlockLevel: 5 },
  { id: 'volcano', name: 'Eldberget', emoji: '🌋', description: 'Bestäm Eldberget', duration: 60, difficulty: 'normal', reward: { xp: 700, coins: 350, kc: 8 }, unlockLevel: 8 },
  { id: 'astral', name: 'Astral Rift', emoji: '🌌', description: 'Resa i dimensioner', duration: 120, difficulty: 'hard', reward: { xp: 1500, coins: 800, kc: 20 }, unlockLevel: 12 },
]

// ── Fish types ────────────────────────────────────────────────────────────────
export const FISH_TYPES: FishType[] = [
  { id: 'bass', name: 'Gädda', emoji: '🐟', rarity: 'common', weight: [0.3, 2.5], coins: 10, xp: 15, chance: 0.35 },
  { id: 'carp', name: 'Karp', emoji: '🫧', rarity: 'common', weight: [0.5, 4.0], coins: 12, xp: 18, chance: 0.25 },
  { id: 'trout', name: 'Öring', emoji: '🍣', rarity: 'uncommon', weight: [0.8, 5.0], coins: 25, xp: 35, chance: 0.15 },
  { id: 'goldfish', name: 'Guldfisk', emoji: '🐠', rarity: 'uncommon', weight: [0.1, 0.5], coins: 30, xp: 45, chance: 0.10 },
  { id: 'moon', name: 'Månfisk', emoji: '🌙', rarity: 'rare', weight: [5.0, 20.0], coins: 80, xp: 100, chance: 0.07 },
  { id: 'crystal', name: 'Kristallfisk', emoji: '💎', rarity: 'rare', weight: [1.0, 8.0], coins: 100, xp: 120, chance: 0.04 },
  { id: 'dragon', name: 'Dragonfisk', emoji: '🐉', rarity: 'epic', weight: [10.0, 50.0], coins: 250, xp: 300, chance: 0.025 },
  { id: 'ghost', name: 'Spöklax', emoji: '👻', rarity: 'legendary', weight: [20.0, 100.0], coins: 1000, xp: 1500, chance: 0.005 },
]

// ── Mission pool (3 picked randomly each day) ─────────────────────────────────
export const MISSION_POOL = [
  { id: 'taps50',    emoji: '👆', label: 'Tryck 50 gånger',   type: 'taps'   as const, target: 50,  reward: { coins: 30,  xp: 50  } },
  { id: 'taps100',   emoji: '⚡', label: 'Tryck 100 gånger',  type: 'taps'   as const, target: 100, reward: { coins: 60,  xp: 100 } },
  { id: 'battle3',   emoji: '⚔️', label: 'Vinn 3 strider',   type: 'battle' as const, target: 3,   reward: { coins: 80,  xp: 100, kc: 2 } },
  { id: 'battle5',   emoji: '🏆', label: 'Vinn 5 strider',   type: 'battle' as const, target: 5,   reward: { coins: 150, xp: 200, kc: 3 } },
  { id: 'feed3',     emoji: '🍖', label: 'Mata 3 gånger',    type: 'feed'   as const, target: 3,   reward: { coins: 40,  xp: 60  } },
  { id: 'feed5',     emoji: '🥩', label: 'Mata 5 gånger',    type: 'feed'   as const, target: 5,   reward: { coins: 70,  xp: 90  } },
  { id: 'fish3',     emoji: '🎣', label: 'Fånga 3 fiskar',   type: 'fish'   as const, target: 3,   reward: { coins: 60,  xp: 80  } },
  { id: 'fish7',     emoji: '🐟', label: 'Fånga 7 fiskar',   type: 'fish'   as const, target: 7,   reward: { coins: 120, xp: 150, kc: 1 } },
  { id: 'runner100', emoji: '🏃', label: 'Spring 100m',      type: 'runner' as const, target: 100, reward: { coins: 40,  xp: 60  } },
  { id: 'runner200', emoji: '💨', label: 'Spring 200m',      type: 'runner' as const, target: 200, reward: { coins: 80,  xp: 100 } },
  { id: 'memory1',   emoji: '🃏', label: 'Klara Memory',     type: 'memory' as const, target: 1,   reward: { coins: 40,  xp: 60  } },
  { id: 'memory3',   emoji: '🎴', label: 'Klara Memory 3×',  type: 'memory' as const, target: 3,   reward: { coins: 100, xp: 150, kc: 1 } },
]

// ── Spin wheel ────────────────────────────────────────────────────────────────
export const SPIN_PRIZES = [
  { label: '50 Mynt', emoji: '🪙', coins: 50, xp: 0, kc: 0, weight: 25 },
  { label: '100 Mynt', emoji: '💰', coins: 100, xp: 0, kc: 0, weight: 20 },
  { label: '200 Mynt', emoji: '🤑', coins: 200, xp: 0, kc: 0, weight: 15 },
  { label: '100 XP', emoji: '⭐', coins: 0, xp: 100, kc: 0, weight: 20 },
  { label: '300 XP', emoji: '🌟', coins: 0, xp: 300, kc: 0, weight: 12 },
  { label: '5 KC', emoji: '✨', coins: 0, xp: 0, kc: 5, weight: 5 },
  { label: '10 KC', emoji: '💎', coins: 0, xp: 0, kc: 10, weight: 2 },
  { label: 'Max Humör!', emoji: '😊', coins: 0, xp: 0, kc: 0, weight: 1 },
]

// ── Battle NPCs ───────────────────────────────────────────────────────────────
export const BATTLE_NPCS = [
  { name: 'Katten Whiskers',  emoji: '😺', hp: 80,   atk: 8,  def: 4,  reward: { coins: 20,  xp: 30  } },
  { name: 'Draken Zorb',      emoji: '🐲', hp: 120,  atk: 12, def: 6,  reward: { coins: 40,  xp: 60  } },
  { name: 'Björnen Grump',    emoji: '🐻', hp: 200,  atk: 18, def: 10, reward: { coins: 80,  xp: 120 } },
  { name: 'Tigern Raze',      emoji: '🐯', hp: 350,  atk: 28, def: 15, reward: { coins: 150, xp: 200 } },
  { name: 'Kosmisk Boss',     emoji: '👾', hp: 600,  atk: 45, def: 25, reward: { coins: 400, xp: 500, kc: 10 } },
  { name: 'Varulven Hex',     emoji: '🐺', hp: 280,  atk: 22, def: 13, reward: { coins: 110, xp: 160 } },
  { name: 'Eldspåren Inferno',emoji: '🔥', hp: 450,  atk: 35, def: 20, reward: { coins: 220, xp: 300, kc: 5 } },
  { name: 'Isgolem Frostbyte',emoji: '❄️', hp: 800,  atk: 50, def: 35, reward: { coins: 500, xp: 700, kc: 15 } },
  { name: 'Galaxkungen',       emoji: '🌌', hp: 1200, atk: 70, def: 45, reward: { coins: 800, xp: 1000, kc: 25 } },
  { name: 'Sommargudinna',    emoji: '🌸', hp: 500,  atk: 40, def: 22, reward: { coins: 300, xp: 450, kc: 8 } },
  { name: 'Neonvarg',        emoji: '🐺', hp: 900,  atk: 60, def: 38, reward: { coins: 600, xp: 850, kc: 20 } },
  { name: 'Forntids-Phoenix', emoji: '🦅', hp: 1500, atk: 85, def: 55, reward: { coins: 1000, xp: 1400, kc: 35 } },
  { name: 'Kaosguden',       emoji: '💀', hp: 2000, atk: 100, def: 65, reward: { coins: 1500, xp: 2000, kc: 50 } },
]

// ── Seasonal event ─────────────────────────────────────────────────────────────
export const SUMMER_FESTIVAL_END = new Date('2026-09-01').getTime()
export const SUMMER_FESTIVAL_MULT = 1.25

// ── Flash feed sample posts ───────────────────────────────────────────────────
export const FLASH_SAMPLE_POSTS = [
  { id: 'f1', username: 'LunaDrake', petEmoji: '🐉', petLevel: 8, caption: 'Min drake nådde nivå 8!! 🔥🔥🔥', likes: 142, xpReward: 15, tag: '#levelup', liked: false },
  { id: 'f2', username: 'StarPaws', petEmoji: '🐱', petLevel: 5, caption: 'Dagens dagliga bonus var EPISK ✨', likes: 87, xpReward: 10, tag: '#daily', liked: false },
  { id: 'f3', username: 'ZenMaster', petEmoji: '🐼', petLevel: 12, caption: 'Klarat 30-dagarsstreaken 🏅 Aldrig missat en dag!', likes: 356, xpReward: 20, tag: '#streak', liked: false },
  { id: 'f4', username: 'VoidHunter', petEmoji: '🐺', petLevel: 15, caption: 'Boss beaten! Kosmisk boss är ned 💪', likes: 221, xpReward: 25, tag: '#battle', liked: false },
  { id: 'f5', username: 'AquaFisher', petEmoji: '🐸', petLevel: 7, caption: 'Fångade Spöklax!! Legendärt! 👻', likes: 512, xpReward: 30, tag: '#fishing', liked: false },
  { id: 'f6', username: 'NeonRacer', petEmoji: '🦊', petLevel: 10, caption: 'Runner highscore: 847m 🏃‍♂️💨', likes: 178, xpReward: 15, tag: '#runner', liked: false },
  { id: 'f7', username: 'MysticKat', petEmoji: '🐯', petLevel: 20, caption: 'Level 20 GOAT achievement unlocked 🔱 Det tog månader!', likes: 899, xpReward: 50, tag: '#achievement', liked: false },
  { id: 'f8', username: 'CosmicPup', petEmoji: '🐶', petLevel: 3, caption: 'Ny i spelet men älskar det! 🐾', likes: 64, xpReward: 8, tag: '#newplayer', liked: false },
  { id: 'f9', username: 'PixelKing', petEmoji: '🦁', petLevel: 18, caption: '2048 CLEAR 🔢🏆 Hämtade 500 mynt direkt!', likes: 445, xpReward: 35, tag: '#2048', liked: false },
  { id: 'f10', username: 'ShadowBear', petEmoji: '🐻', petLevel: 6, caption: 'Soulmate bond med min björn 💫 500 bond points!', likes: 203, xpReward: 20, tag: '#bond', liked: false },
  { id: 'f11', username: 'GalaxPet', petEmoji: '🦄', petLevel: 25, caption: 'PRESTIGE LV3 erreicht 💎💎💎 vi ses i toppen!', likes: 1024, xpReward: 60, tag: '#prestige', liked: false },
  { id: 'f12', username: 'TunaHunter', petEmoji: '🦈', petLevel: 9, caption: 'Fiskespelet gav mig 3 legendärer på rad 🎣🎣🎣', likes: 388, xpReward: 25, tag: '#fishing', liked: false },
  { id: 'f13', username: 'QuietPanda', petEmoji: '🐼', petLevel: 4, caption: 'Craftat min första Regnbåge-Kit ✨ stats maxade!', likes: 77, xpReward: 12, tag: '#craft', liked: false },
  { id: 'f14', username: 'EliteWolf', petEmoji: '🐺', petLevel: 30, caption: '100 stridssegrar!! Oövervinnerlig ⚔️👑', likes: 2048, xpReward: 75, tag: '#battle', liked: false },
  { id: 'f15', username: 'CosmoKat', petEmoji: '🐱', petLevel: 14, caption: 'Lyckhjulet snurrade på 5 KC!! 🎰💎 Dag 3 av rad!', likes: 631, xpReward: 30, tag: '#lucky', liked: false },
  { id: 'f16', username: 'SpeedRunner', petEmoji: '🦅', petLevel: 11, caption: 'NY REKORD 1243m i Runner! 🏃💨 Beat my old 890!', likes: 289, xpReward: 22, tag: '#runner', liked: false },
  { id: 'f17', username: 'CrystalMage', petEmoji: '🦋', petLevel: 17, caption: 'Expedition till Astral Rift klar 🌌 +1500 XP värd varje minut!', likes: 540, xpReward: 40, tag: '#expedition', liked: false },
  { id: 'f18', username: 'NovaFox', petEmoji: '🦊', petLevel: 13, caption: 'Soulmate tier med min räv!! Det tog 1500 bond points 💚', likes: 712, xpReward: 45, tag: '#bond', liked: false },
  { id: 'f19', username: 'BlazeKnight', petEmoji: '🔥', petLevel: 22, caption: 'Skin "Fire" + Aura "Fire" = ultimate look 🔥🔥🔥 tryck på mig', likes: 853, xpReward: 35, tag: '#fashion', liked: false },
  { id: 'f20', username: 'QuantumPup', petEmoji: '🐶', petLevel: 8, caption: 'Första veckan klar! Tipps till nya: mata varje dag 🍖🐾', likes: 156, xpReward: 15, tag: '#tips', liked: false },
  { id: 'f21', username: 'TitanPanda', petEmoji: '🐼', petLevel: 45, caption: 'Level 45. Prestige 2. 50,000 pek. Det är dedication 🏆✨', likes: 3201, xpReward: 100, tag: '#milestone', liked: false },
  { id: 'f22', username: 'GhostWhale', petEmoji: '👻', petLevel: 19, caption: 'Fångade Spöklax IGEN — twice in one session!! RNG GOD 🎣', likes: 924, xpReward: 50, tag: '#fishing', liked: false },
]

// ── Feature Hub entries ───────────────────────────────────────────────────────
export const FEATURE_HUB_ITEMS = [
  { id: 'spin', emoji: '🎡', label: 'Daglig Spin', desc: 'Snurra hjulet dagligen' },
  { id: 'lucky', emoji: '📦', label: 'Lucky Box', desc: 'Öppna en belöningslåda' },
  { id: 'chests', emoji: '🎁', label: 'Kistor', desc: 'Daglig gratis kista' },
  { id: 'bounty', emoji: '📌', label: 'Uppdragstavla', desc: 'Hämta belöningar' },
  { id: 'checkin', emoji: '📅', label: 'Daglig Check-in', desc: 'Hämta daglig belöning' },
  { id: 'skilltree', emoji: '🌳', label: 'Kompetensträd', desc: 'Uppgradera passiva förmågor' },
  { id: 'tarot', emoji: '🔮', label: 'Tarotkort', desc: 'Daglig tarot-läsning' },
  { id: 'trophyroom', emoji: '🏆', label: 'Pokalrum', desc: 'Dina prestationstrofeer' },
  { id: 'mine', emoji: '⛏️', label: 'Gruvan', desc: 'Passiv myntinkomst' },
  { id: 'farm', emoji: '🌾', label: 'Gården', desc: 'Odla grödor & skörda' },
  { id: 'worldevents', emoji: '🌍', label: 'Världshändelser', desc: 'Live events & bonusar' },
  { id: 'dnalab', emoji: '🧬', label: 'DNA Lab', desc: 'Brygga fusioner' },
  { id: 'bank', emoji: '🏦', label: 'Banken', desc: 'Sätt in mynt & tjäna ränta' },
  { id: 'worldboss', emoji: '🐉', label: 'World Boss', desc: 'Vecklig boss-räd' },
  { id: 'petjournal', emoji: '📖', label: 'Husdjursdagbok', desc: 'Din husdjurs historia' },
  { id: 'tournament', emoji: '🏆', label: 'Turnering', desc: 'Daglig tävling med priser' },
  { id: 'companion', emoji: '🐾', label: 'Följeslagare', desc: 'Passiva bonus-husdjur' },
  { id: 'auction', emoji: '🔨', label: 'Auktionshuset', desc: 'Bjud på sällsynta föremål' },
  { id: 'activitylog', emoji: '📜', label: 'Aktivitet', desc: 'Din spelhistorik' },
  { id: 'shop', emoji: '🛍️', label: 'Shop', desc: 'Köp kosmetika & boosts' },
  { id: 'expedition', emoji: '🗺️', label: 'Expedition', desc: 'Skicka husdjuret på äventyr' },
  { id: 'achievements', emoji: '🏆', label: 'Prestationer', desc: 'Se dina utmärkelser' },
  { id: 'craft', emoji: '⚗️', label: 'Craftshop', desc: 'Skapa föremål' },
  { id: 'fishpedia', emoji: '🐟', label: 'Fiskpedia', desc: 'Din fisksamling' },
  { id: 'fortune', emoji: '🥠', label: 'Lyckobudskap', desc: 'Daglig visdom' },
  { id: 'wardrobe', emoji: '👗', label: 'Garderob', desc: 'Klä din husdjur' },
  { id: 'battlepass', emoji: '🎫', label: 'Battle Pass', desc: 'Säsongsbelöningar' },
  { id: 'leaderboard', emoji: '🏅', label: 'Topplista', desc: 'Se rankningen' },
  { id: 'quests', emoji: '📋', label: 'Dagliga Quests', desc: 'Klara uppdrag' },
  { id: 'records', emoji: '📊', label: 'Rekord', desc: 'Dina personliga rekord' },
  { id: 'prestigehall', emoji: '🔱', label: 'Prestige Hall', desc: 'Prestige & legendariska belöningar' },
  { id: 'clan', emoji: '🛡️', label: 'Klanen', desc: 'Gå med i ett klan' },
  { id: 'lottery', emoji: '🎟️', label: 'Lotteriet', desc: 'Daglig chans på storvinst' },
  { id: 'spa', emoji: '🛁', label: 'Pet Spa', desc: 'Pamper ditt husdjur' },
  { id: 'challenges', emoji: '🎯', label: 'Utmaningar', desc: 'Svåra dagliga uppdrag' },
  { id: 'traits', emoji: '🧬', label: 'Traits', desc: 'Passiva bonus-egenskaper' },
  { id: 'roulette', emoji: '🎰', label: 'Roulette', desc: 'Satsa på röd, svart eller siffra' },
  { id: 'mailbox', emoji: '📬', label: 'Brevlåda', desc: 'Presenter & meddelanden' },
  { id: 'cookbook', emoji: '📖', label: 'Kokboken', desc: 'Laga speciella krafträtter' },
  { id: 'bond', emoji: '💚', label: 'Band', desc: 'Din anknytning till husdjuret' },
  { id: 'training', emoji: '💪', label: 'Träning', desc: 'Träna husdjurets förmågor' },
  { id: 'petcare', emoji: '🩺', label: 'Husdjursvård', desc: 'Daglig vård & hälsostatus' },
  { id: 'flashsale', emoji: '⚡', label: 'Flash Sale', desc: 'Tidsbegränsade erbjudanden' },
  { id: 'giftshop', emoji: '🎁', label: 'Presentbutik', desc: 'Exklusiva KC-gåvor' },
  { id: 'milestones', emoji: '🏁', label: 'Milstolpar', desc: 'Livsmålande milstolpar' },
  { id: 'seasonal', emoji: '🌸', label: 'Säsongspass', desc: 'Säsongens specialuppdrag' },
  { id: 'trading', emoji: '🔄', label: 'Handelspost', desc: 'Köp & sälj föremål' },
  { id: 'forge', emoji: '⚒️', label: 'Smedjan', desc: 'Smid mäktiga föremål' },
  { id: 'enchant', emoji: '✨', label: 'Förtrollning', desc: 'Förtrolla för tillfälliga bonusar' },
  { id: 'museum', emoji: '🏛️', label: 'Museet', desc: 'Din samling & statistik' },
  { id: 'pvprank', emoji: '🥊', label: 'PvP Rang', desc: 'Din rang bland alla spelare' },
  { id: 'inventory', emoji: '🎒', label: 'Ryggsäck', desc: 'Alla dina ägda föremål' },
  { id: 'events', emoji: '📆', label: 'Händelser', desc: 'Kommande event & bonusar' },
  { id: 'stickers', emoji: '🌟', label: 'Klistermärken', desc: 'Samla & visa klistermärken' },
  { id: 'gifting', emoji: '🎀', label: 'Gåvor', desc: 'Skicka gåvor till vänner' },
  { id: 'pethome', emoji: '🏠', label: 'Husdjurshus', desc: 'Bygg & dekorera hemmet' },
  { id: 'potions', emoji: '🧪', label: 'Bryggeriet', desc: 'Brygga mäktiga drycker' },
  { id: 'arena2', emoji: '🏟️', label: 'Grand Arena', desc: 'Avancerat PvP-läge' },
  { id: 'cosmetics', emoji: '💅', label: 'Kosmetika', desc: 'Se alla upplåsta utseenden' },
  { id: 'garden', emoji: '🌻', label: 'Trädgård', desc: 'Plantera & skörda blommor' },
  { id: 'rescue', emoji: '🦺', label: 'Räddningsuppdrag', desc: 'Rädda husdjur & få belöningar' },
  { id: 'stats', emoji: '📈', label: 'Statistik', desc: 'Djupanalys av din spelhistorik' },
  { id: 'leaguetable', emoji: '🥇', label: 'Ligatabell', desc: 'Veckovinnare & topplista' },
  { id: 'badges', emoji: '🎖️', label: 'Märken', desc: 'Specialmärken & utmärkelser' },
  { id: 'wishlist', emoji: '✍️', label: 'Önskelista', desc: 'Spara föremål du vill ha' },
  { id: 'meditation', emoji: '🧘', label: 'Meditation', desc: 'Lugna ner & boosta humör' },
  { id: 'petdiary', emoji: '📓', label: 'Husdjursdagbok', desc: 'Dagliga anteckningar & minnen' },
  { id: 'petshowcase', emoji: '🌟', label: 'Showcase', desc: 'Visa upp ditt husdjur' },
  { id: 'petgym', emoji: '🏋️', label: 'Husdjursgym', desc: 'Träna husdjuret & boosta stats' },
  { id: 'hatchery', emoji: '🥚', label: 'Ruveri', desc: 'Kläck ägg och få belöningar' },
  { id: 'cosmicmap', emoji: '🗺️', label: 'Kosmisk Karta', desc: 'Utforska galaxen & hitta skatter' },
  { id: 'petschool', emoji: '🎓', label: 'Husdjursskola', desc: 'Lär husdjuret nya tricks' },
  { id: 'mysterybox', emoji: '🎁', label: 'Mysterybox', desc: 'Öppna lådor för okända belöningar' },
  { id: 'petfusion', emoji: '⚗️', label: 'Pet Fusion', desc: 'Kombinera element för bonusar' },
  { id: 'carnival', emoji: '🎡', label: 'Karneval', desc: 'Spel & priser på karnevalen' },
  { id: 'petbirthday', emoji: '🎂', label: 'Födelsedag', desc: 'Fira husdjurets födelsedag' },
  { id: 'royaltytree', emoji: '👑', label: 'Stamtavla', desc: 'Husdjurets familjeträd & arv' },
  { id: 'speedrun', emoji: '⏱️', label: 'Speedrun', desc: 'Tidsutmaningar & rekordlistor' },
  { id: 'collectibles', emoji: '🏺', label: 'Samlarföremål', desc: 'Sällsynta föremål & utställning' },
  { id: 'petparade', emoji: '🎪', label: 'Husdjursparad', desc: 'Visa upp husdjuret i paraden' },
  { id: 'shrine', emoji: '⛩️', label: 'Altaret', desc: 'Offra & välsigna ditt husdjur' },
  { id: 'timecapsule', emoji: '💌', label: 'Tidskapsel', desc: 'Skicka meddelanden till framtiden' },
  { id: 'constellation', emoji: '✨', label: 'Stjärnbild', desc: 'Hitta ditt husdjurs stjärntecken' },
  { id: 'habitat', emoji: '🏡', label: 'Habitat', desc: 'Bygg och anpassa husdjurets hem' },
  { id: 'petcoach', emoji: '🎯', label: 'Tränare', desc: 'Personlig coach med dagliga tips' },
  { id: 'nextevent', emoji: '📅', label: 'Kalender', desc: 'Kommande events & specialdagar' },
  { id: 'chronicle', emoji: '📖', label: 'Krönika', desc: 'Husdjurets äventyrshistoria' },
  { id: 'rewards', emoji: '🎁', label: 'Belöningar', desc: 'Dagliga & veckovisa belöningar' },
  { id: 'petmood', emoji: '💆', label: 'Välmående', desc: 'Detaljerad humör & hälsotracker' },
  { id: 'petalbum', emoji: '📸', label: 'Album', desc: 'Foton & minnen från äventyren' },
  { id: 'skillpoints', emoji: '🎓', label: 'Färdigheter', desc: 'Fördela färdighetspoäng' },
  { id: 'socialcenter', emoji: '🤝', label: 'Socialt', desc: 'Skicka gåvor & möt vänner' },
  { id: 'weather', emoji: '🌤', label: 'Väder', desc: 'In-game väder & bonusar' },
  { id: 'worldranking', emoji: '🌍', label: 'Världsranking', desc: 'Se hur du rankar globalt' },
  { id: 'petlore', emoji: '📜', label: 'Historia', desc: 'Din husdjursarts lore & bakgrund' },
  { id: 'petevolution', emoji: '🔄', label: 'Evolution', desc: 'Husdjurets evolutions och former' },
  { id: 'battlestats', emoji: '📊', label: 'Stridstatistik', desc: 'Detaljerad strid- och kampstatistik' },
  { id: 'itemcollection', emoji: '🗃️', label: 'Samling', desc: 'Galleri över alla samlade föremål' },
  { id: 'petspirit', emoji: '🔮', label: 'Andedjur', desc: 'Husdjurets andedjur & stjärntecken' },
  { id: 'moodboard', emoji: '🎨', label: 'Moodboard', desc: 'Visuell inspirationstavla' },
  { id: 'nightshift', emoji: '🌙', label: 'Nattskift', desc: 'Passiv intjäning medan du sover' },
  { id: 'petritual', emoji: '🕯️', label: 'Ritualer', desc: 'Dagliga ritualer för bonusar' },
  { id: 'marketplace', emoji: '🏪', label: 'Marknad', desc: 'Köp & sälj med andra spelare' },
  { id: 'encyclopedia', emoji: '📚', label: 'Encyklopedi', desc: 'Allt om husdjursvärlden' },
  { id: 'petgoals', emoji: '🎯', label: 'Mål', desc: 'Sätt och följ upp personliga mål' },
  { id: 'energyboost', emoji: '⚡', label: 'Energiboost', desc: 'Köp tillfälliga energiboosters' },
  { id: 'petfunfacts', emoji: '🤓', label: 'Husdjursfakta', desc: 'Roliga fakta om ditt husdjur' },
  { id: 'petvillage', emoji: '🏘️', label: 'Husdjursby', desc: 'Bygg och förvalta din husdjursby' },
  { id: 'powerups', emoji: '🚀', label: 'Kraftboosters', desc: 'Aktivera kraftfulla tillfälliga boosters' },
  { id: 'petrank', emoji: '🏅', label: 'Husdjursrang', desc: 'Klättra i rangen med din husdjur' },
  { id: 'dreamworld', emoji: '💤', label: 'Drömvärld', desc: 'Utforska husdjurets drömmar och visioner' },
  { id: 'elementals', emoji: '🌊', label: 'Element', desc: 'Lär husdjuret elementala krafter' },
  { id: 'petlegacy', emoji: '📖', label: 'Arv', desc: 'Husdjurets legendariska arvshistoria' },
  { id: 'pettavern', emoji: '🍺', label: 'Krog', desc: 'Träffa NPC-karaktärer och utbyt uppdrag' },
  { id: 'relicvault', emoji: '🏺', label: 'Relikvalv', desc: 'Samla och utforska sällsynta reliker' },
  { id: 'petastrology', emoji: '🌙', label: 'Astrologi', desc: 'Husdjurets stjärntecken och horoskop' },
  { id: 'petcalendar', emoji: '📅', label: 'Kalender', desc: 'Planera och spåra husdjurshändelser' },
  { id: 'petmemories', emoji: '📸', label: 'Minnen', desc: 'Galleri med husdjurets bästa stunder' },
  { id: 'alchemylab', emoji: '🧪', label: 'Alkemin', desc: 'Kombinera ingredienser för kraftfulla effekter' },
  { id: 'petsanctuary', emoji: '🌿', label: 'Helgedom', desc: 'Husdjurets fridfullt naturliga tillflyktsort' },
  { id: 'cosmicshop', emoji: '🌌', label: 'Kosmisk Butik', desc: 'Sällsynta kosmiska föremål och uppgraderingar' },
  { id: 'petprowess', emoji: '💪', label: 'Skicklighet', desc: 'Träna och förbättra husdjurets specialförmågor' },
  { id: 'pettraining2', emoji: '🏋️', label: 'Träningsläger', desc: 'Intensivt träningsläger för attributboost' },
  { id: 'guildhouse', emoji: '🏰', label: 'Gillesal', desc: 'Gå med i ett gille och delta i gilleuppdrag' },
  { id: 'seasonpass', emoji: '🎫', label: 'Säsongspass', desc: 'Exklusiva säsongsbelöningar och utmaningar' },
  { id: 'petkarma', emoji: '🪬', label: 'Karma', desc: 'Goda handlingar ger karma och XP-bonusar' },
  { id: 'worldmap', emoji: '🗺️', label: 'Världskarta', desc: 'Utforska zoner och lås upp belöningar' },
  { id: 'petfestival', emoji: '🎪', label: 'Festival', desc: 'Säsongsfestival med exklusiva event-belöningar' },
  { id: 'dailychest', emoji: '📦', label: 'Daglig Kista', desc: 'Öppna en kista varje dag för slumpmässiga belöningar' },
  { id: 'petcircus', emoji: '🎡', label: 'Husdjurscirkus', desc: 'Cirkusakter och trick för XP och roliga belöningar' },
  { id: 'stargazing', emoji: '🌠', label: 'Stjärnkikare', desc: 'Observera nattskyn och samla stjärnkraft' },
  { id: 'petdojo', emoji: '🥋', label: 'Dojo', desc: 'Träna kampsport och lär husdjuret tekniker' },
  { id: 'timetravel', emoji: '⏳', label: 'Tidsresor', desc: 'Utforska husdjurets historia och framtid' },
  { id: 'petnews', emoji: '📰', label: 'Nyheter', desc: 'Senaste nyheter från husdjursvärlden' },
  { id: 'petlotus', emoji: '🪷', label: 'Lotusö', desc: 'Meditativ ö för husdjuret att vila och återhämta sig' },
  { id: 'speedrune', emoji: '⚡', label: 'Speedrunor', desc: 'Lås upp runostenar för passiva bonusar' },
  { id: 'pethive', emoji: '🐝', label: 'Bigård', desc: 'Sköt bigården och samla honung för mynt' },
  { id: 'petgarden2', emoji: '🌻', label: 'Solrosträdgård', desc: 'Odla solrosor för dagliga mynt och XP' },
  { id: 'petmuseum2', emoji: '🗿', label: 'Antikvitetsmuseum', desc: 'Samla antika artefakter och bygg ut museet' },
  { id: 'petdisco', emoji: '🪩', label: 'Disco', desc: 'Dansa med husdjuret för humörboost och XP' },
  { id: 'petspa2', emoji: '🛁', label: 'Lyxspa', desc: 'Exklusiva spa-behandlingar för maxad återhämtning' },
  { id: 'petpolarexp', emoji: '🧊', label: 'Polarexpedition', desc: 'Utforska arktiska ishallar för sällsynta fynd' },
  { id: 'petgauntlet', emoji: '⚔️', label: 'Prövningens Gata', desc: 'En serie av utmaningar för legendärt belöning' },
  { id: 'petodyssey', emoji: '🚀', label: 'Husdjursodessey', desc: 'Episk rymdresa med ditt husdjur till okänd galax' },
  { id: 'petarcade', emoji: '🕹️', label: 'Husdjursarkad', desc: 'Klassiska arkadspel med ditt husdjur som hjälte' },
  { id: 'petchampion', emoji: '🏆', label: 'Mästarskapsbälte', desc: 'Utmana världens bästa och erövra mästarskapet' },
  { id: 'petlibrary', emoji: '📚', label: 'Husdjursbibliotek', desc: 'Lär dig fakta om djur och öka din kunskap' },
  { id: 'petsorcerer', emoji: '🧙', label: 'Trollkarlens torn', desc: 'Lär dig magi och lås upp hemliga förmågor' },
  { id: 'pettheatre', emoji: '🎭', label: 'Husdjursteatern', desc: 'Sätt upp pjäser och tjäna applåder och priser' },
  { id: 'petgallery', emoji: '🖼️', label: 'Konstgalleriet', desc: 'Visa upp ditt husdjurs konstverk och samla fans' },
  { id: 'petvolcano', emoji: '🌋', label: 'Vulkanbasen', desc: 'Dykäventyr i lava — extrem belöning för det modiga' },
  { id: 'petcrossroads', emoji: '🔮', label: 'Korsvägen', desc: 'Välj din öde väg vid den magiska korsvägen' },
  { id: 'petlabyrint', emoji: '🌀', label: 'Husdjurslabyrint', desc: 'Navigera labyrinten och hitta de dolda skatterna' },
  { id: 'petairdrop', emoji: '🪂', label: 'Luftlandning', desc: 'Fallskärmshopp med ditt husdjur för bonusar' },
  { id: 'petatelier', emoji: '🎨', label: 'Konstnärsateliern', desc: 'Skapa mästerverk och sälj dem på konstmarknaden' },
  { id: 'petunderworld', emoji: '🌑', label: 'Underjorden', desc: 'En mörk resa till underjorden för sällsynta reliker' },
  { id: 'petcosmos', emoji: '🌌', label: 'Kosmosresan', desc: 'Navigera galaxer och samla stardamm för uppgraderingar' },
  { id: 'pethonorhall', emoji: '🏛️', label: 'Ärans Hall', desc: 'Belöna ditt husdjur för deras prestationer och minnen' },
  { id: 'petsummit', emoji: '⛰️', label: 'Toppen', desc: 'Nå toppen och se världen från det högsta berget' },
  { id: 'petpirate', emoji: '🏴‍☠️', label: 'Piratloppet', desc: 'Segla haven och hitta dolda skattöar' },
  { id: 'petmechanic', emoji: '🔧', label: 'Verkstaden', desc: 'Bygg och uppgradera din husdjursutrustning' },
  { id: 'petdungeon2', emoji: '🏰', label: 'Fästningens djup', desc: 'En svårare dungeon med bossfiende på sista våningen' },
  { id: 'petaquarium', emoji: '🐠', label: 'Akvarium', desc: 'Bygg ditt eget akvarium och låt fiskar växa' },
  { id: 'petbakery', emoji: '🥐', label: 'Bageriet', desc: 'Baka läckerheter och sälj dem i butiken' },
  { id: 'petflorist', emoji: '🌸', label: 'Blomsterbutiken', desc: 'Odla och sälj blommor för mynt' },
  { id: 'petworkshop', emoji: '🔧', label: 'Verkstaden', desc: 'Hantverk och uppgraderingar för ditt husdjur' },
  { id: 'petmuseum3', emoji: '🏛️', label: 'Museet', desc: 'Samla artefakter som ger passiv XP-bonus' },
  { id: 'petjungle', emoji: '🌴', label: 'Djungeln', desc: 'Utforska djungeln och hitta skatter' },
  { id: 'petsalon2', emoji: '💈', label: 'Salong', desc: 'Ge ditt husdjur en makeover och få bond' },
  { id: 'petcamp', emoji: '⛺', label: 'Lägret', desc: 'Campa ute och samla naturresurser' },
  { id: 'petisland', emoji: '🏝️', label: 'Ön', desc: 'Tropisk ö med dagliga aktiviteter' },
  { id: 'petlighthouse', emoji: '🏮', label: 'Fyren', desc: 'Vakta fyren och vägled fartyg för XP' },
  { id: 'petbeekeeper', emoji: '🐝', label: 'Bigården', desc: 'Skörda honung och sälj för mynt' },
  { id: 'petgarden3', emoji: '🌼', label: 'Trädgård III', desc: 'Säsongsbaserad trädgård med unika växter' },
  { id: 'petspacebase', emoji: '🛸', label: 'Rymdbasen', desc: 'Hantera din rymdstation och forska' },
  { id: 'petclinic', emoji: '🏥', label: 'Kliniken', desc: 'Bota sjuka djur och tjäna mynt' },
  { id: 'petdiner', emoji: '🍔', label: 'Dinern', desc: 'Servera mat och tjäna mynt i restaurangen' },
  { id: 'petskatepark', emoji: '🛹', label: 'Skatepark', desc: 'Utför tricks med husdjuret för XP' },
  { id: 'petstudio', emoji: '🎬', label: 'Studion', desc: 'Spela in videos med ditt husdjur för bond' },
  { id: 'petspeedway', emoji: '🏎️', label: 'Speedway', desc: 'Tävla på banan med husdjuret för mynt' },
  { id: 'petsunset', emoji: '🌅', label: 'Solnedgången', desc: 'Varva ner med husdjuret och ladda energi' },
  { id: 'petmarket', emoji: '🏪', label: 'Marknaden', desc: 'Handla och sälj föremål på marknaden' },
  { id: 'petobservatory', emoji: '🔭', label: 'Observatoriet', desc: 'Titta på stjärnor och samla kosmisk XP' },
  { id: 'petbowling', emoji: '🎳', label: 'Bowlinghallen', desc: 'Bowla med husdjuret och vinn mynt' },
  { id: 'petcinema', emoji: '🎥', label: 'Biografen', desc: 'Se filmer med husdjuret och stärk bondet' },
  { id: 'petvolleyball', emoji: '🏐', label: 'Volleyboll', desc: 'Spela volleyboll med husdjuret för XP' },
  { id: 'petgreenhouse', emoji: '🌿', label: 'Växthuset', desc: 'Odla exotiska växter för bond och mynt' },
  { id: 'petchef', emoji: '👨‍🍳', label: 'Chefsköket', desc: 'Laga gourmetmat med husdjuret för belöningar' },
  { id: 'petmoonbase', emoji: '🌙', label: 'Månbasen', desc: 'Bygg och hantera månbasen med husdjuret' },
  { id: 'petsurfer', emoji: '🏄', label: 'Surfen', desc: 'Surfa med husdjuret på havet för XP' },
  { id: 'petlaboratory', emoji: '🧪', label: 'Laboratoriet', desc: 'Forska och experimentera för bond och XP' },
  { id: 'petvolcanolair', emoji: '🌋', label: 'Vulkangrottan', desc: 'Utforska vulkanen och smid eldföremål' },
  { id: 'petrobotics', emoji: '🤖', label: 'Robotlabbet', desc: 'Bygg robotar som tjänar mynt åt dig' },
  { id: 'petjunglecamp', emoji: '🌴', label: 'Djungelläger', desc: 'Övernatta i djungeln och samla resurser' },
  { id: 'peticecastle', emoji: '🧊', label: 'Isslottet', desc: 'Frys fiender och samla isresurser' },
  { id: 'petpirateship', emoji: '🏴‍☠️', label: 'Piratskepp', desc: 'Segla till skatterna med husdjuret' },
  { id: 'petmagictower', emoji: '🗼', label: 'Magtornet', desc: 'Lär husdjuret magiska förmågor' },
  { id: 'petdragonlair', emoji: '🐉', label: 'Drakgrotta', desc: 'Husdjuret tränar med draken för makt' },
  { id: 'petskyisland', emoji: '☁️', label: 'Himmelsön', desc: 'Flytande ö i molnen med hemligheter' },
  { id: 'petstormkeep', emoji: '⛈️', label: 'Stormfästet', desc: 'Betvinga stormarna och skörda energi' },
  { id: 'petcryptmine', emoji: '⛏️', label: 'Kryptogruvan', desc: 'Mina digitala kristaller för mynt' },
  { id: 'petsolartower', emoji: '☀️', label: 'Solartornet', desc: 'Samla solenergi och konvertera till XP' },
  { id: 'pettidalcave', emoji: '🌊', label: 'Tidsgrottan', desc: 'Dykarexpedition med tidsportaler' },
  { id: 'petcandylab', emoji: '🍭', label: 'Godislabbet', desc: 'Skapa godis och sälj för mynt' },
  { id: 'petspacestation', emoji: '🛸', label: 'Rymdstationen', desc: 'Bemanna stationen och forska för XP' },
  { id: 'petmysticforest', emoji: '🌲', label: 'Mystiska Skogen', desc: 'Utforska trollskogen och samla bond' },
  { id: 'petvolcanicforge', emoji: '🌋', label: 'Vulkansmeden', desc: 'Smid vapen i lavan för mynt och XP' },
  { id: 'petcloudrider', emoji: '☁️', label: 'Molnryttaren', desc: 'Rida på moln och samla stjärnor för bond' },
  { id: 'petarcticsled', emoji: '🛷', label: 'Arktisslädden', desc: 'Kör hundspann och hämta kc-poäng' },
  { id: 'petdeepocean', emoji: '🌊', label: 'Djuphavsbasen', desc: 'Bygg undervattensbas och forska för XP' },
  { id: 'petdragonvalley', emoji: '🐉', label: 'Draksänkan', desc: 'Träna drakar och samla drakguld för mynt' },
  { id: 'petstarlodge', emoji: '🌠', label: 'Stjärnlogen', desc: 'Nattliga observationer ger bond och XP' },
  { id: 'petcryptvault', emoji: '🏛️', label: 'Kryptkistan', desc: 'Öppna gamla valv och hitta skatter för mynt' },
  { id: 'petsunflower', emoji: '🌻', label: 'Solrosfältet', desc: 'Skörda solrosor för bond och XP' },
  { id: 'petwindmill', emoji: '🏗️', label: 'Väderkvarnen', desc: 'Mala säd och baka bröd för mynt och bond' },
  { id: 'petglacier', emoji: '🧊', label: 'Glaciärlabbet', desc: 'Forska i is och samla unika resurser för XP' },
  { id: 'petcoralreef', emoji: '🐚', label: 'Korallrevet', desc: 'Utforska koraller och samla bond och mynt' },
  { id: 'petsavanna', emoji: '🦁', label: 'Savannen', desc: 'Guida djur och tjäna mynt och XP' },
  { id: 'petmushroom', emoji: '🍄', label: 'Svampriket', desc: 'Plocka svamp och brygga trolldryck för XP' },
  { id: 'petwatchtower', emoji: '🗼', label: 'Vakttornet', desc: 'Vakta landet och samla mynt och KC' },
  { id: 'petbeach', emoji: '🏖️', label: 'Stranden', desc: 'Relaxa på stranden och bygg sandslott för bond' },
  { id: 'petsnowglobe', emoji: '🌨️', label: 'Snöglödet', desc: 'Bygga snöfigurer och vinterfiranden för bond' },
  { id: 'petjeweler', emoji: '💍', label: 'Smyckesmeden', desc: 'Skapa smycken och sälj för mynt och XP' },
  { id: 'petcloudcastle', emoji: '🏯', label: 'Molnslottet', desc: 'Driva ett flygande slott och samla mynt' },
  { id: 'petbeekeeper2', emoji: '🍯', label: 'Biodlaren', desc: 'Skörda honung och sälj på marknaden för mynt' },
  { id: 'petrobotfactory', emoji: '🤖', label: 'Robotfabriken', desc: 'Bygg robotar och tjäna KC och XP' },
  { id: 'petherbgarden', emoji: '🌿', label: 'Örtagården', desc: 'Odla örter och brygga te för bond' },
  { id: 'petpirateisland', emoji: '🏴‍☠️', label: 'Piratön', desc: 'Gräv efter skatten och hämta mynt och XP' },
  { id: 'petlighthouse2', emoji: '💡', label: 'Fyrtornet', desc: 'Guida skepp säkert hem och samla mynt och bond' },
  { id: 'petastronautbase', emoji: '🚀', label: 'Astronautbasen', desc: 'Träna astronauter och forska för XP och KC' },
  { id: 'petcookielab', emoji: '🍪', label: 'Kakfabriken', desc: 'Baka cookies och sälj dem för mynt och bond' },
  { id: 'petjunglebase', emoji: '🌴', label: 'Djungelbasen', desc: 'Utforska djungeln och samla exotiska resurser' },
  { id: 'peticehotel', emoji: '🧊', label: 'Ishotellet', desc: 'Driv ett ishotell och samla mynt och XP' },
  { id: 'petdragonegg', emoji: '🥚', label: 'Drakägget', desc: 'Rugga fram drakägg och sälj för mynt och KC' },
  { id: 'petfireworks', emoji: '🎆', label: 'Fyrverkeri', desc: 'Sätt upp shower och samla bond och mynt' },
  { id: 'petunderwater', emoji: '🐠', label: 'Undervattensvärlden', desc: 'Utforska djupet och samla XP och bond' },
  { id: 'petvolcano3', emoji: '🌋', label: 'Lavabadet', desc: 'Badda i vulkanisk lava och samla energi för XP' },
  { id: 'petmagicshop', emoji: '🔮', label: 'Magikbutiken', desc: 'Sälj magiska föremål för mynt och KC' },
  { id: 'petsnowfort', emoji: '❄️', label: 'Snöfästet', desc: 'Bygg och försvara snöfästet för bond och mynt' },
  { id: 'petspiderweb', emoji: '🕷️', label: 'Spindelvävet', desc: 'Väv silke och fånga insekter för mynt och XP' },
  { id: 'petsunrise', emoji: '🌅', label: 'Soluppgången', desc: 'Mäktig vistelse vid soluppgången för bond och XP' },
  { id: 'petmeteor', emoji: '☄️', label: 'Meteoritlabbet', desc: 'Studera meteoriter och samla KC och XP' },
  { id: 'petancientruins', emoji: '🏛️', label: 'Fornruinerna', desc: 'Gräv ut fornlämningar och samla XP och KC' },
  { id: 'petmushroom2', emoji: '🍄', label: 'Svampgrottan', desc: 'Odla magiska svampar för bond och mynt' },
  { id: 'petcrystalriver', emoji: '💧', label: 'Kristallfloden', desc: 'Fiska kristaller ur floden för mynt och XP' },
  { id: 'petwindpark', emoji: '💨', label: 'Vindparken', desc: 'Drifta vindkraftverk och samla energimynt och XP' },
  { id: 'petstonehenge2', emoji: '🗿', label: 'Stenmonumentet', desc: 'Arrangera stenar och hitta mystisk kraft för KC' },
  { id: 'petcomics', emoji: '📚', label: 'Serietidningen', desc: 'Skapa serier och sälj dem för mynt och bond' },
  { id: 'petmusicbox', emoji: '🎵', label: 'Musikboxen', desc: 'Spela melodier med husdjuret och tjäna mynt och XP' },
  { id: 'petvolcanocave', emoji: '🌋', label: 'Vulkangrotta 2', desc: 'Aktivera vulkanutbrott och samla KC och XP' },
  { id: 'petjunglelodge', emoji: '🌿', label: 'Djungelhyddan', desc: 'Utforska djungeln med husdjuret och hitta skatter' },
  { id: 'petbotanicgarden', emoji: '🌸', label: 'Botaniska Trädgården', desc: 'Vårda sällsynta blommor och tjäna bond och mynt' },
  { id: 'petsubmarine', emoji: '🤿', label: 'Ubåtsbasen', desc: 'Utforska djuphavet och hämta upp XP och KC' },
  { id: 'petastrolab', emoji: '🔭', label: 'Astrolabiet', desc: 'Studera stjärnor och hitta kosmisk energi för XP' },
  { id: 'petclockwork', emoji: '⚙️', label: 'Urmakaren', desc: 'Bygg klockor och mekanismer för mynt och XP' },
  { id: 'peticelab', emoji: '🧊', label: 'Islaboratoriet', desc: 'Forska i is och kyla — tjäna KC och bond' },
  { id: 'petflamingo', emoji: '🦩', label: 'Flamingodansen', desc: 'Dans med flamingon och vinn mynt och XP' },
  { id: 'petsandcastle', emoji: '🏖️', label: 'Sandslottet', desc: 'Bygg sandslott och tjäna bond och mynt' },
  { id: 'petneonmarket', emoji: '🌃', label: 'Neonmarknaden', desc: 'Handla på nattmarknaden för mynt och XP' },
  { id: 'petcrypthall', emoji: '🗝️', label: 'Kryptvalvet', desc: 'Lås upp hemliga rum och samla KC och XP' },
  { id: 'petstormhaven', emoji: '⛈️', label: 'Stormhavnen', desc: 'Skydda husdjuret från stormen och samla XP och KC' },
  { id: 'petlunartemple', emoji: '🌕', label: 'Måntemplet', desc: 'Genomför månritualer och tjäna bond och mynt' },
  { id: 'petdriftwood', emoji: '🪵', label: 'Drivvedsön', desc: 'Bygg flotte av drivved och utforska havet för KC' },
]

// ── Fortune cookie messages ────────────────────────────────────────────────────
export const FORTUNE_MESSAGES = [
  'Din kraft växer med varje pek. 🌟',
  'Äventyr väntar den modige. 🗺️',
  'Din husdjur älskar dig mer än du vet. 💖',
  'Lyckan ler mot den som fortsätter. 🍀',
  'Ett leende kostar ingenting men ger allt. 😊',
  'Varje dag är en ny chans att bli starkare. ⚡',
  'Skatter hittas av de som söker. 💎',
  'Din streak är ett bevis på din dedikation. 🔥',
  'De stora bossarna fruktar dig. ⚔️',
  'Stjärnorna lyser för dig ikväll. ✨',
  'Den som tappar aldrig uppger aldrig. 💪',
  'En liten seger varje dag leder till storhet. 🏆',
  'Karma belönar dem som tar hand om sina husdjur. 🐾',
  'Din nästa level-up är nästan här — håll ut! 📈',
  'Utmaningarna formar den starka. 🔱',
  'Havet av möjligheter öppnas för den djärve. 🌊',
  'Idag är du bättre än gårdagens version. 🌅',
  'Varje mynt du tjänar är ett steg mot greatness. 💰',
  'Ditt husdjur drömmer om era äventyr. 🌙',
  'Mysteriet väntar — öppna det och se. 🔮',
  'Draken inom dig väntar på att väckas. 🐉',
  'Kom ihåg: konstans slår talang. 📅',
  'Den regnbågen efter stormen är din. 🌈',
  'Universum whispers: du är på rätt väg. 🌌',
  'Fiskarna vet att du kommer. 🎣',
  'Din aura expanderar med varje positiv handling. ✨',
  'Det börjar med en tanke — sedan händer allt. 💭',
  'Starka hjärtan bygger starka husdjur. ❤️',
  'Snabbhet vinner ibland; uthållighet vinner alltid. 🏃',
  'En legend börjar med ett enda steg. 👣',
]

// ── Lucky box prizes ───────────────────────────────────────────────────────────
export const LUCKY_PRIZES = [
  { emoji: '💰', label: '500 Mynt', coins: 500, kc: 0, xp: 0 },
  { emoji: '⚡', label: '1000 Mynt', coins: 1000, kc: 0, xp: 0 },
  { emoji: '💎', label: '10 KC', coins: 0, kc: 10, xp: 0 },
  { emoji: '🌟', label: '200 XP', coins: 0, kc: 0, xp: 200 },
  { emoji: '🎁', label: '50 KC', coins: 0, kc: 50, xp: 0 },
  { emoji: '🍀', label: '2000 Mynt', coins: 2000, kc: 0, xp: 0 },
  { emoji: '🏆', label: '100 KC', coins: 0, kc: 100, xp: 0 },
  { emoji: '✨', label: '500 XP', coins: 0, kc: 0, xp: 500 },
]
